# Generated by Django 3.1.5 on 2021-01-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='album.binding'),
        ),
        migrations.AddField(
            model_name='album',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='album.template'),
        ),
    ]
