# Generated by Django 3.1.5 on 2021-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20210129_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
